# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "04:00"
      timezone: "Europe/Berlin"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    target-branch: "master"
    commit-message:
      include: "scope"
      prefix: "composer"
    target-branch: "master"

  # actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Europe/Berlin"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    open-pull-requests-limit: 10
    assignees:
      - "mimmi20"
    labels:
      - "dependencies"
    commit-message:
      prefix: "github-actions"
    target-branch: "master"
    ignore:
      - dependency-name: "mimmi20/ci"
      - dependency-name: "release-drafter/release-drafter"
